export default {
  content: [
    './index.html',
    './src/**/*.{js,jsx,ts,tsx}'
  ],
  theme: {
    extend: {
      backgroundColor: {
        'bg': 'var(--bg)',
        'black-5': 'var(--black-5)',
        'black-8': 'var(--black-8)',
        'black-10': 'var(--black-10)',
        'black-15': 'var(--black-15)',
        'light': 'var(--light)',
        'blue-primary': 'var(--blue-primary)',
        'blue-secondary': 'var(--blue-secondary)',
        'red-primary': 'var(--red-primary)',
        'red-secondary': 'var(--red-secondary)',
        'yellow-primary': 'var(--yellow-primary)',
        'yellow-secondary': 'var(--yellow-secondary)',
        'green-primary': 'var(--green-primary)',
        'green-secondary': 'var(--green-secondary)',
        'purple-primary': 'var(--purple-primary)',
        'purple-secondary': 'var(--purple-secondary)',
        'pink-primary': 'var(--pink-primary)',
        'pink-secondary': 'var(--pink-secondary)',
        'orange-primary': 'var(--orange-primary)',
        'orange-secondary': 'var(--orange-secondary)',
        'darkblue-primary': 'var(--darkblue-primary)',
        'darkblue-secondary': 'var(--darkblue-secondary)',
        'alan': 'var(--alan)',
        'donatien': 'var(--donatien)',
        'lucien': 'var(--lucien)',
        'virginie': 'var(--virginie)',
        'barbara': 'var(--barbara)',
        'alex': 'var(--alex)',
        'lucie': 'var(--lucie)',
        'tanguy': 'var(--tanguy)',
      },
      textColor: {
        'bg': 'var(--bg)',
        'light': 'var(--light)',
        'blue-primary': 'var(--blue-primary)',
        'blue-secondary': 'var(--blue-secondary)',
        'red-primary': 'var(--red-primary)',
        'red-secondary': 'var(--red-secondary)',
        'yellow-primary': 'var(--yellow-primary)',
        'yellow-secondary': 'var(--yellow-secondary)',
        'green-primary': 'var(--green-primary)',
        'green-secondary': 'var(--green-secondary)',
        'purple-primary': 'var(--purple-primary)',
        'purple-secondary': 'var(--purple-secondary)',
        'pink-primary': 'var(--pink-primary)',
        'pink-secondary': 'var(--pink-secondary)',
        'orange-primary': 'var(--orange-primary)',
        'orange-secondary': 'var(--orange-secondary)',
        'darkblue-primary': 'var(--darkblue-primary)',
        'darkblue-secondary': 'var(--darkblue-secondary)',
        'alan': 'var(--alan)',
        'donatien': 'var(--donatien)',
        'lucien': 'var(--lucien)',
        'virginie': 'var(--virginie)',
        'barbara': 'var(--barbara)',
        'alex': 'var(--alex)',
        'lucie': 'var(--lucie)',
        'tanguy': 'var(--tanguy)',
      },
      borderColor: {
        'bg': 'var(--bg)',
        'light': 'var(--light)',
        'blue-primary': 'var(--blue-primary)',
        'blue-secondary': 'var(--blue-secondary)',
        'red-primary': 'var(--red-primary)',
        'red-secondary': 'var(--red-secondary)',
        'yellow-primary': 'var(--yellow-primary)',
        'yellow-secondary': 'var(--yellow-secondary)',
        'green-primary': 'var(--green-primary)',
        'green-secondary': 'var(--green-secondary)',
        'purple-primary': 'var(--purple-primary)',
        'purple-secondary': 'var(--purple-secondary)',
        'pink-primary': 'var(--pink-primary)',
        'pink-secondary': 'var(--pink-secondary)',
        'orange-primary': 'var(--orange-primary)',
        'orange-secondary': 'var(--orange-secondary)',
        'darkblue-primary': 'var(--darkblue-primary)',
        'darkblue-secondary': 'var(--darkblue-secondary)',
        'alan': 'var(--alan)',
        'donatien': 'var(--donatien)',
        'lucien': 'var(--lucien)',
        'virginie': 'var(--virginie)',
        'barbara': 'var(--barbara)',
        'alex': 'var(--alex)',
        'lucie': 'var(--lucie)',
        'tanguy': 'var(--tanguy)',
      }
    }
  }
}