const { createHarness, emitWithAck, waitForEvent } = require('./helpers/mainServer')
const { createPlayers, enterGameLoop, roomState } = require('./helpers/game')
const harness = createHarness()
jest.setTimeout(75000)
beforeEach(harness.start)
afterEach(harness.stop)

test('undo during creation survives the old drawing deadline and preserves the replacement quiz', async () => {
  const clients = await createPlayers(harness, 2)
  const [host, guest] = clients
  await enterGameLoop(clients)
  await emitWithAck(host, 'trigger_action', 'ACTIVITE')
  host.emit('activite_acknowledge_ready')
  await roomState(host)
  const creating = waitForEvent(host, 'update_room_state', room => room.status === 'ACTIVITE_CREATION')
  guest.emit('activite_acknowledge_ready')
  await creating
  expect((await emitWithAck(host, 'undo_last_action', {})).ok).toBe(true)
  expect((await roomState(host)).status).toBe('GAME_LOOP')
  await emitWithAck(host, 'trigger_action', 'QUIZ')
  const options = await roomState(host)
  await emitWithAck(host, 'start_specific_quiz', { difficulty: options.availableQuizDifficulties[0] })
  const quiz = await roomState(host)
  expect(quiz.status).toBe('INTERACTION')
  await new Promise(resolve => setTimeout(resolve, 61000))
  const afterDeadline = await roomState(host)
  expect(afterDeadline.status).toBe('INTERACTION')
  expect(afterDeadline.currentInteraction).toEqual(quiz.currentInteraction)
})

test('activity readiness and drawing submissions cannot restart later phases', async () => {
  const clients = await createPlayers(harness, 2)
  const [host, guest] = clients
  await enterGameLoop(clients)
  await emitWithAck(host, 'trigger_action', 'ACTIVITE')
  host.emit('activite_acknowledge_ready')
  await roomState(host)
  guest.emit('activite_acknowledge_ready')
  expect((await roomState(guest)).status).toBe('ACTIVITE_CREATION')
  host.emit('activite_submit_drawing')
  await roomState(host)
  guest.emit('activite_submit_drawing')
  const upload = await roomState(guest)
  expect(upload.status).toBe('ACTIVITE_UPLOAD')
  expect(await emitWithAck(host, 'activite_acknowledge_ready', {})).toMatchObject({ ok: false })
  expect(await emitWithAck(guest, 'activite_submit_drawing', {})).toMatchObject({ ok: false })
  expect((await roomState(host)).currentInteraction).toEqual(upload.currentInteraction)
})
